var Module = function(Module) {
  Module = Module || {};

var d;d||(d=typeof Module !== 'undefined' ? Module : {});d.TOTAL_MEMORY=65536;d.TOTAL_STACK=32768;d.preInit=function(){aa=ba=65536};
d.instantiateWasm=function(a,b){return function(a){return new Promise(function(b,c){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){b(e.response)};e.onerror=function(){c("error "+e.status)};e.send(null)})}("/hello.wasm?v=1c682e4e9553703d8c87dbc78d005538").then(function(c){return WebAssembly.instantiate(new Uint8Array(c),a).then(function(c){b(c.instance);a.parent.then=null;return Promise.resolve(a.parent)})}).catch(function(a){ca();throw a;})};var n={},r;
for(r in d)d.hasOwnProperty(r)&&(n[r]=d[r]);d.arguments=[];d.thisProgram="./this.program";d.quit=function(a,b){throw b;};d.preRun=[];d.postRun=[];var t=!1,u=!1,da=!1,ea=!1;t="object"===typeof window;u="function"===typeof importScripts;da="object"===typeof process&&"function"===typeof require&&!t&&!u;ea=!t&&!da&&!u;
if(da){var fa,ha;d.read=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);a=fa.readFileSync(a);return b?a:a.toString()};d.readBinary=function(a){a=d.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(d.thisProgram=process.argv[1].replace(/\\/g,"/"));d.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",function(){process.exit(1)});d.quit=function(a){process.exit(a)};
d.inspect=function(){return"[Emscripten Module object]"}}else if(ea)"undefined"!=typeof read&&(d.read=function(a){return read(a)}),d.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?d.arguments=scriptArgs:"undefined"!=typeof arguments&&(d.arguments=arguments),"function"===typeof quit&&(d.quit=function(a){quit(a)});else if(t||u)d.read=function(a){var b=new XMLHttpRequest;
b.open("GET",a,!1);b.send(null);return b.responseText},u&&(d.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),d.readAsync=function(a,b,c){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)},d.setWindowTitle=function(a){document.title=a};
var ia=d.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),v=d.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ia);for(r in n)n.hasOwnProperty(r)&&(d[r]=n[r]);n=void 0;function ja(a){var b;b||(b=16);return Math.ceil(a/b)*b}var ka={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},la=0;function assert(a,b){a||w("Assertion failed: "+b)}
function ma(a){var b;if(0===b||!a)return"";for(var c=0,e,g=0;;){e=x[a+g>>0];c|=e;if(0==e&&!b)break;g++;if(b&&g==b)break}b||(b=g);e="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,x.subarray(a,a+Math.min(b,1024))),e=e?e+c:c,a+=1024,b-=1024;return e}return na(x,a)}var oa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function na(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&oa)return oa.decode(a.subarray(b,c));for(c="";;){var e=a[b++];if(!e)return c;if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;if(224==(e&240))e=(e&15)<<12|g<<6|f;else{var h=a[b++]&63;if(240==(e&248))e=(e&7)<<18|g<<12|f<<6|h;else{var l=a[b++]&63;if(248==(e&252))e=(e&3)<<24|g<<18|f<<12|h<<6|l;else{var q=a[b++]&63;e=(e&1)<<30|g<<24|f<<18|h<<12|l<<6|q}}}65536>e?c+=String.fromCharCode(e):(e-=
65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}}
function pa(a,b,c,e){if(0<e){e=c+e-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);55296<=f&&57343>=f&&(f=65536+((f&1023)<<10)|a.charCodeAt(++g)&1023);if(127>=f){if(c>=e)break;b[c++]=f}else{if(2047>=f){if(c+1>=e)break;b[c++]=192|f>>6}else{if(65535>=f){if(c+2>=e)break;b[c++]=224|f>>12}else{if(2097151>=f){if(c+3>=e)break;b[c++]=240|f>>18}else{if(67108863>=f){if(c+4>=e)break;b[c++]=248|f>>24}else{if(c+5>=e)break;b[c++]=252|f>>30;b[c++]=128|f>>24&63}b[c++]=128|f>>18&63}b[c++]=128|f>>12&63}b[c++]=
128|f>>6&63}b[c++]=128|f&63}}b[c]=0}}function qa(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:2097151>=e?b+4:67108863>=e?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var ba=16777216,aa=16777216;function ra(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,y,x,sa,ta,z,A,ua,va;
function wa(){d.HEAP8=y=new Int8Array(buffer);d.HEAP16=sa=new Int16Array(buffer);d.HEAP32=z=new Int32Array(buffer);d.HEAPU8=x=new Uint8Array(buffer);d.HEAPU16=ta=new Uint16Array(buffer);d.HEAPU32=A=new Uint32Array(buffer);d.HEAPF32=ua=new Float32Array(buffer);d.HEAPF64=va=new Float64Array(buffer)}var B,C,xa,ya,za,Aa,D;B=C=xa=ya=za=Aa=D=0;
d.reallocBuffer||(d.reallocBuffer=function(a){try{if(ArrayBuffer.M)var b=ArrayBuffer.M(buffer,a);else{var c=y;b=new ArrayBuffer(a);(new Int8Array(b)).set(c)}}catch(e){return!1}return Ba(b)?b:!1});var Ca;try{Ca=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),Ca(new ArrayBuffer(4))}catch(a){Ca=function(b){return b.byteLength}}var Da=d.TOTAL_STACK||5242880,F=d.TOTAL_MEMORY||16777216;
F<Da&&v("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+F+"! (TOTAL_STACK="+Da+")");d.buffer?buffer=d.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(d.wasmMemory=new WebAssembly.Memory({initial:F/65536}),buffer=d.wasmMemory.buffer):buffer=new ArrayBuffer(F),d.buffer=buffer);wa();
function G(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.s;"number"===typeof c?void 0===b.o?d.dynCall_v(c):d.dynCall_vi(c,b.o):c(void 0===b.o?null:b.o)}}}var Ea=[],Fa=[],Ga=[],Ha=[],Ia=!1;function Ja(){var a=d.preRun.shift();Ea.unshift(a)}var H=0,Ka=null,J=null;function ca(){H--;d.monitorRunDependencies&&d.monitorRunDependencies(H);if(0==H&&(null!==Ka&&(clearInterval(Ka),Ka=null),J)){var a=J;J=null;a()}}d.preloadedImages={};d.preloadedAudios={};
function La(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(d.wasmBinary)return new Uint8Array(d.wasmBinary);if(d.readBinary)return d.readBinary(g);throw"on the web, we need the wasm binary to be preloaded and set on Module['wasmBinary']. emcc.py will do that for you when generating HTML (but not JS)";}catch(m){w(m)}}function b(){return d.wasmBinary||!t&&!u||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(g,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+g+
"'";return a.arrayBuffer()}).catch(function(){return a()})}function c(a){function c(a){l=a.exports;if(l.memory){a=l.memory;var b=d.buffer;a.byteLength<b.byteLength&&v("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);d.buffer=buffer=a;wa()}d.asm=l;d.usingWasm=!0;ca()}function e(a){c(a.instance)}function E(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a).catch(function(a){v("failed to asynchronously prepare wasm: "+
a);w(a)})}if("object"!==typeof WebAssembly)return v("no native wasm support detected"),!1;if(!(d.wasmMemory instanceof WebAssembly.Memory))return v("no native wasm Memory in use"),!1;a.memory=d.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;H++;d.monitorRunDependencies&&d.monitorRunDependencies(H);if(d.instantiateWasm)try{return d.instantiateWasm(h,c)}catch(k){return v("Module.instantiateWasm callback failed with error: "+k),!1}d.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
La(g)||"function"!==typeof fetch?E(e):WebAssembly.instantiateStreaming(fetch(g,{credentials:"same-origin"}),h).then(e).catch(function(a){v("wasm streaming compile failed: "+a);v("falling back to ArrayBuffer instantiation");E(e)});return{}}var e="hello.wast",g="hello.wasm",f="hello.temp.asm.js";"function"===typeof d.locateFile&&(La(e)||(e=d.locateFile(e)),La(g)||(g=d.locateFile(g)),La(f)||(f=d.locateFile(f)));var h={global:null,env:null,asm2wasm:ka,parent:d},l=null;d.asmPreload=d.asm;var q=d.reallocBuffer;
d.reallocBuffer=function(a){if("asmjs"===p)var b=q(a);else a:{a=ra(a,d.usingWasm?65536:ba);var c=d.buffer.byteLength;if(d.usingWasm)try{b=-1!==d.wasmMemory.grow((a-c)/65536)?d.buffer=d.wasmMemory.buffer:null;break a}catch(E){b=null;break a}b=void 0}return b};var p="";d.asm=function(a,b){if(!b.table){a=d.wasmTableSize;void 0===a&&(a=1024);var e=d.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):
new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);d.wasmTable=b.table}b.memoryBase||(b.memoryBase=d.STATIC_BASE);b.tableBase||(b.tableBase=0);b=c(b);assert(b,"no binaryen method succeeded.");return b}})();B=1024;C=B+24464;Fa.push({s:function(){Ma()}},{s:function(){Na()}},{s:function(){Oa()}});d.STATIC_BASE=B;d.STATIC_BUMP=24464;C+=16;function Pa(a){d.___errno_location&&(z[d.___errno_location()>>2]=a);return a}var K=0;function M(){K+=4;return z[K-4>>2]}var N={};
function O(a,b){K=b;try{var c=M(),e=M(),g=M();a=0;O.b||(O.b=[null,[],[]],O.u=function(a,b){var c=O.b[a];assert(c);0===b||10===b?((1===a?ia:v)(na(c,0)),c.length=0):c.push(b)});for(b=0;b<g;b++){for(var f=z[e+8*b>>2],h=z[e+(8*b+4)>>2],l=0;l<h;l++)O.u(c,x[f+l]);a+=h}return a}catch(q){return"undefined"!==typeof FS&&q instanceof FS.i||w(q),-q.j}}function Qa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ra=void 0;
function Q(a){for(var b="";x[a];)b+=Ra[x[a++]];return b}var R={},S={},Sa={};function Ta(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ua(a,b){a=Ta(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Va(a){var b=Error,c=Ua(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Wa=void 0;function U(a){throw new Wa(a);}var Ya=void 0;
function Za(a,b){var c=[];function e(a){a=b(a);if(a.length!==c.length)throw new Ya("Mismatched type converter count");for(var e=0;e<c.length;++e)V(c[e],a[e])}c.forEach(function(b){Sa[b]=a});var g=Array(a.length),f=[],h=0;a.forEach(function(a,b){S.hasOwnProperty(a)?g[b]=S[a]:(f.push(a),R.hasOwnProperty(a)||(R[a]=[]),R[a].push(function(){g[b]=S[a];++h;h===f.length&&e(g)}))});0===f.length&&e(g)}
function V(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||U('type "'+e+'" must have a positive integer typeid pointer');if(S.hasOwnProperty(a)){if(c.F)return;U("Cannot register type '"+e+"' twice")}S[a]=b;delete Sa[a];R.hasOwnProperty(a)&&(b=R[a],delete R[a],b.forEach(function(a){a()}))}var $a=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function ab(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=$a.length?$a.pop():W.length;W[b]={H:1,value:a};return b}}function bb(a){return this.fromWireType(A[a>>2])}function cb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function db(a,b){switch(b){case 2:return function(a){return this.fromWireType(ua[a>>2])};case 3:return function(a){return this.fromWireType(va[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}function eb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ua(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function gb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function hb(a,b){var c=d;if(void 0===c[a].c){var e=c[a];c[a]=function(){c[a].c.hasOwnProperty(arguments.length)||U("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].c+")!");return c[a].c[arguments.length].apply(this,arguments)};c[a].c=[];c[a].c[e.A]=e}}
function ib(a,b,c){d.hasOwnProperty(a)?((void 0===c||void 0!==d[a].c&&void 0!==d[a].c[c])&&U("Cannot register public name '"+a+"' twice"),hb(a,a),d.hasOwnProperty(c)&&U("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),d[a].c[c]=b):(d[a]=b,void 0!==c&&(d[a].X=c))}function jb(a,b){for(var c=[],e=0;e<a;e++)c.push(z[(b>>2)+e]);return c}
function kb(a,b){a=Q(a);if(void 0!==d["FUNCTION_TABLE_"+a])var c=d["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=d.asm["dynCall_"+a];void 0===c&&(c=d.asm["dynCall_"+a.replace(/f/g,"d")],void 0===c&&U("No dynCall invoker for signature: "+a));for(var e=[],g=1;g<a.length;++g)e.push("a"+g);g="return function "+("dynCall_"+a+"_"+b)+"("+e.join(", ")+") {\n";g+="    return dynCall(rawFunction"+(e.length?", ":"")+e.join(", ")+");\n";c=(new Function("dynCall",
"rawFunction",g+"};\n"))(c,b)}"function"!==typeof c&&U("unknown function pointer with signature "+a+": "+b);return c}var lb=void 0;function mb(a){a=nb(a);var b=Q(a);X(a);return b}function ob(a,b){function c(a){g[a]||S[a]||(Sa[a]?Sa[a].forEach(c):(e.push(a),g[a]=!0))}var e=[],g={};b.forEach(c);throw new lb(a+": "+e.map(mb).join([", "]));}
function pb(a,b,c){switch(b){case 0:return c?function(a){return y[a]}:function(a){return x[a]};case 1:return c?function(a){return sa[a>>1]}:function(a){return ta[a>>1]};case 2:return c?function(a){return z[a>>2]}:function(a){return A[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var qb={};function Y(a){if(0===a)return 0;a=ma(a);if(!qb.hasOwnProperty(a))return 0;Y.b&&X(Y.b);a=qb[a];var b=qa(a)+1,c=rb(b);c&&pa(a,y,c,b);Y.b=c;return Y.b}
function Z(){Z.b||(Z.b=[]);Z.b.push(sb());return Z.b.length-1}function tb(a){return 0===a%4&&(0!==a%100||0===a%400)}function ub(a,b){for(var c=0,e=0;e<=b;c+=a[e++]);return c}var vb=[31,29,31,30,31,30,31,31,30,31,30,31],wb=[31,28,31,30,31,30,31,31,30,31,30,31];
function xb(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),e=(tb(a.getFullYear())?vb:wb)[c];if(b>e-a.getDate())b-=e-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function yb(a,b,c,e){function g(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function f(a,b){return g(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var e;0===(e=c(a.getFullYear()-b.getFullYear()))&&0===(e=c(a.getMonth()-b.getMonth()))&&(e=c(a.getDate()-b.getDate()));return e}function l(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function q(a){a=xb(new Date(a.a+1900,0,1),a.m);var b=l(new Date(a.getFullYear()+1,0,4));return 0>=h(l(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var p=z[e+40>>2];e={K:z[e>>2],J:z[e+4>>2],l:z[e+8>>2],h:z[e+12>>2],g:z[e+16>>2],a:z[e+20>>2],w:z[e+24>>2],m:z[e+28>>2],Y:z[e+32>>2],I:z[e+36>>2],L:p?ma(p):""};
c=ma(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var m in p)c=c.replace(new RegExp(m,"g"),p[m]);var I="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),P="January February March April May June July August September October November December".split(" ");p={"%a":function(a){return I[a.w].substring(0,3)},"%A":function(a){return I[a.w]},"%b":function(a){return P[a.g].substring(0,
3)},"%B":function(a){return P[a.g]},"%C":function(a){return f((a.a+1900)/100|0,2)},"%d":function(a){return f(a.h,2)},"%e":function(a){return g(a.h,2," ")},"%g":function(a){return q(a).toString().substring(2)},"%G":function(a){return q(a)},"%H":function(a){return f(a.l,2)},"%I":function(a){a=a.l;0==a?a=12:12<a&&(a-=12);return f(a,2)},"%j":function(a){return f(a.h+ub(tb(a.a+1900)?vb:wb,a.g-1),3)},"%m":function(a){return f(a.g+1,2)},"%M":function(a){return f(a.J,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=
a.l&&12>a.l?"AM":"PM"},"%S":function(a){return f(a.K,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.a+1900,a.g+1,a.h,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.a+1900,0,1),c=0===b.getDay()?b:xb(b,7-b.getDay());a=new Date(a.a+1900,a.g,a.h);return 0>h(c,a)?f(Math.ceil((31-c.getDate()+(ub(tb(a.getFullYear())?vb:wb,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=l(new Date(a.a+1900,0,4)),c=l(new Date(a.a+1901,0,4)),e=xb(new Date(a.a+
1900,0,1),a.m);return 0>h(e,b)?"53":0>=h(c,e)?"01":f(Math.ceil((b.getFullYear()<a.a+1900?a.m+32-b.getDate():a.m+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.a+1900,a.g+1,a.h,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.a,0,1),c=1===b.getDay()?b:xb(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.a+1900,a.g,a.h);return 0>h(c,a)?f(Math.ceil((31-c.getDate()+(ub(tb(a.getFullYear())?vb:wb,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%y":function(a){return(a.a+1900).toString().substring(2)},
"%Y":function(a){return a.a+1900},"%z":function(a){a=a.I;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.L},"%%":function(){return"%"}};for(m in p)0<=c.indexOf(m)&&(c=c.replace(new RegExp(m,"g"),p[m](e)));m=zb(c);if(m.length>b)return 0;y.set(m,a);return m.length-1}for(var Ab=Array(256),Bb=0;256>Bb;++Bb)Ab[Bb]=String.fromCharCode(Bb);Ra=Ab;Wa=d.BindingError=Va("BindingError");Ya=d.InternalError=Va("InternalError");
d.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};d.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};lb=d.UnboundTypeError=Va("UnboundTypeError");var Cb=C;C=C+4+15&-16;D=Cb;xa=ya=ja(C);za=xa+Da;Aa=ja(za);z[D>>2]=Aa;function zb(a){var b=Array(qa(a)+1);pa(a,b,0,b.length);return b}d.wasmTableSize=479;d.wasmMaxTableSize=479;d.B={};
d.C={abort:w,enlargeMemory:function(){var a=d.usingWasm?65536:ba,b=2147483648-a;if(z[D>>2]>b)return!1;var c=F;for(F=Math.max(F,aa);F<z[D>>2];)536870912>=F?F=ra(2*F,a):F=Math.min(ra((3*F+2147483648)/4,a),b);a=d.reallocBuffer(F);if(!a||a.byteLength!=F)return F=c,!1;d.buffer=buffer=a;wa();return!0},getTotalMemory:function(){return F},abortOnCannotGrowMemory:function(){w("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+F+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},
___cxa_uncaught_exception:function(){return!!Db.u},___lock:function(){},___map_file:function(){Pa(1);return-1},___setErrNo:Pa,___syscall140:function(a,b){K=b;try{var c=N.v();M();var e=M(),g=M(),f=M();FS.U(c,e,f);z[g>>2]=c.position;c.D&&0===e&&0===f&&(c.D=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof FS.i||w(h),-h.j}},___syscall145:function(a,b){K=b;try{var c=N.v(),e=M(),g=M();return N.P(c,e,g)}catch(f){return"undefined"!==typeof FS&&f instanceof FS.i||w(f),-f.j}},___syscall146:O,
___syscall54:function(a,b){K=b;return 0},___syscall6:function(a,b){K=b;try{var c=N.v();FS.close(c);return 0}catch(e){return"undefined"!==typeof FS&&e instanceof FS.i||w(e),-e.j}},___syscall91:function(a,b){K=b;try{var c=M(),e=M(),g=N.G[c];if(!g)return 0;if(e===g.T){var f=FS.R(g.fd);N.O(c,f,e,g.flags);FS.W(f);N.G[c]=null;g.N&&X(g.V)}return 0}catch(h){return"undefined"!==typeof FS&&h instanceof FS.i||w(h),-h.j}},___unlock:function(){},__embind_register_bool:function(a,b,c,e,g){var f=Qa(c);b=Q(b);V(a,
{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?e:g},argPackAdvance:8,readValueFromPointer:function(a){if(1===c)var e=y;else if(2===c)e=sa;else if(4===c)e=z;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(e[a>>f])},f:null})},__embind_register_emval:function(a,b){b=Q(b);V(a,{name:b,fromWireType:function(a){var b=W[a].value;4<a&&0===--W[a].H&&(W[a]=void 0,$a.push(a));return b},toWireType:function(a,b){return ab(b)},argPackAdvance:8,readValueFromPointer:bb,
f:null})},__embind_register_float:function(a,b,c){c=Qa(c);b=Q(b);V(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+cb(b)+'" to '+this.name);return b},argPackAdvance:8,readValueFromPointer:db(b,c),f:null})},__embind_register_function:function(a,b,c,e,g,f){var h=jb(b,c);a=Q(a);g=kb(e,g);ib(a,function(){ob("Cannot call "+a+" due to unbound types",h)},b-1);Za(h,function(c){var e=[c[0],null].concat(c.slice(1)),
h=c=a,m=g,l=e.length;2>l&&U("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var P=null!==e[1]&&!1,E=!1,k=1;k<e.length;++k)if(null!==e[k]&&void 0===e[k].f){E=!0;break}var Xa="void"!==e[0].name,L="",T="";for(k=0;k<l-2;++k)L+=(0!==k?", ":"")+"arg"+k,T+=(0!==k?", ":"")+"arg"+k+"Wired";h="return function "+Ta(h)+"("+L+") {\nif (arguments.length !== "+(l-2)+") {\nthrowBindingError('function "+h+" called with ' + arguments.length + ' arguments, expected "+(l-2)+" args!');\n}\n";
E&&(h+="var destructors = [];\n");var fb=E?"destructors":"null";L="throwBindingError invoker fn runDestructors retType classParam".split(" ");m=[U,m,f,gb,e[0],e[1]];P&&(h+="var thisWired = classParam.toWireType("+fb+", this);\n");for(k=0;k<l-2;++k)h+="var arg"+k+"Wired = argType"+k+".toWireType("+fb+", arg"+k+"); // "+e[k+2].name+"\n",L.push("argType"+k),m.push(e[k+2]);P&&(T="thisWired"+(0<T.length?", ":"")+T);h+=(Xa?"var rv = ":"")+"invoker(fn"+(0<T.length?", ":"")+T+");\n";if(E)h+="runDestructors(destructors);\n";
else for(k=P?1:2;k<e.length;++k)l=1===k?"thisWired":"arg"+(k-2)+"Wired",null!==e[k].f&&(h+=l+"_dtor("+l+"); // "+e[k].name+"\n",L.push(l+"_dtor"),m.push(e[k].f));Xa&&(h+="var ret = retType.fromWireType(rv);\nreturn ret;\n");L.push(h+"}\n");e=eb(L).apply(null,m);k=b-1;if(!d.hasOwnProperty(c))throw new Ya("Replacing nonexistant public symbol");void 0!==d[c].c&&void 0!==k?d[c].c[k]=e:(d[c]=e,d[c].A=k);return[]})},__embind_register_integer:function(a,b,c,e,g){function f(a){return a}b=Q(b);-1===g&&(g=
4294967295);var h=Qa(c);if(0===e){var l=32-8*c;f=function(a){return a<<l>>>l}}var q=-1!=b.indexOf("unsigned");V(a,{name:b,fromWireType:f,toWireType:function(a,c){if("number"!==typeof c&&"boolean"!==typeof c)throw new TypeError('Cannot convert "'+cb(c)+'" to '+this.name);if(c<e||c>g)throw new TypeError('Passing a number "'+cb(c)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+g+"]!");return q?c>>>0:c|0},argPackAdvance:8,readValueFromPointer:pb(b,
h,0!==e),f:null})},__embind_register_memory_view:function(a,b,c){function e(a){a>>=2;var b=A;return new g(b.buffer,b[a+1],b[a])}var g=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=Q(c);V(a,{name:c,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{F:!0})},__embind_register_std_string:function(a,b){b=Q(b);V(a,{name:b,fromWireType:function(a){for(var b=A[a>>2],c=Array(b),f=0;f<b;++f)c[f]=String.fromCharCode(x[a+4+f]);X(a);return c.join("")},
toWireType:function(a,b){function c(a,b){return a[b]}function e(a,b){return a.charCodeAt(b)}b instanceof ArrayBuffer&&(b=new Uint8Array(b));var h;b instanceof Uint8Array?h=c:b instanceof Uint8ClampedArray?h=c:b instanceof Int8Array?h=c:"string"===typeof b?h=e:U("Cannot pass non-string to std::string");var l=b.length,q=rb(4+l);A[q>>2]=l;for(var p=0;p<l;++p){var m=h(b,p);255<m&&(X(q),U("String has UTF-16 code units that do not fit in 8 bits"));x[q+4+p]=m}null!==a&&a.push(X,q);return q},argPackAdvance:8,
readValueFromPointer:bb,f:function(a){X(a)}})},__embind_register_std_wstring:function(a,b,c){c=Q(c);if(2===b){var e=function(){return ta};var g=1}else 4===b&&(e=function(){return A},g=2);V(a,{name:c,fromWireType:function(a){for(var b=e(),c=A[a>>2],f=Array(c),p=a+4>>g,m=0;m<c;++m)f[m]=String.fromCharCode(b[p+m]);X(a);return f.join("")},toWireType:function(a,c){var f=e(),h=c.length,p=rb(4+h*b);A[p>>2]=h;for(var m=p+4>>g,I=0;I<h;++I)f[m+I]=c.charCodeAt(I);null!==a&&a.push(X,p);return p},argPackAdvance:8,
readValueFromPointer:bb,f:function(a){X(a)}})},__embind_register_void:function(a,b){b=Q(b);V(a,{S:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},_abort:function(){d.abort()},_emscripten_memcpy_big:function(a,b,c){x.set(x.subarray(b,b+c),a);return a},_getenv:Y,_llvm_stackrestore:function(a){var b=Z.b[a];Z.b.splice(a,1);Eb(b)},_llvm_stacksave:Z,_pthread_cond_wait:function(){return 0},_strftime_l:function(a,b,c,e){return yb(a,b,c,e)},DYNAMICTOP_PTR:D,STACKTOP:ya};
var Fb=d.asm(d.B,d.C,buffer);d.asm=Fb;
var Na=d.__GLOBAL__sub_I_bind_cpp=function(){return d.asm.__GLOBAL__sub_I_bind_cpp.apply(null,arguments)},Ma=d.__GLOBAL__sub_I_hello_cc=function(){return d.asm.__GLOBAL__sub_I_hello_cc.apply(null,arguments)},Oa=d.__GLOBAL__sub_I_iostream_cpp=function(){return d.asm.__GLOBAL__sub_I_iostream_cpp.apply(null,arguments)},Db=d.__ZSt18uncaught_exceptionv=function(){return d.asm.__ZSt18uncaught_exceptionv.apply(null,arguments)},nb=d.___getTypeName=function(){return d.asm.___getTypeName.apply(null,arguments)},
Ba=d._emscripten_replace_memory=function(){return d.asm._emscripten_replace_memory.apply(null,arguments)},X=d._free=function(){return d.asm._free.apply(null,arguments)},rb=d._malloc=function(){return d.asm._malloc.apply(null,arguments)},Eb=d.stackRestore=function(){return d.asm.stackRestore.apply(null,arguments)},sb=d.stackSave=function(){return d.asm.stackSave.apply(null,arguments)};d.dynCall_ii=function(){return d.asm.dynCall_ii.apply(null,arguments)};
d.dynCall_iii=function(){return d.asm.dynCall_iii.apply(null,arguments)};d.dynCall_iiii=function(){return d.asm.dynCall_iiii.apply(null,arguments)};d.dynCall_iiiii=function(){return d.asm.dynCall_iiiii.apply(null,arguments)};d.dynCall_iiiiid=function(){return d.asm.dynCall_iiiiid.apply(null,arguments)};d.dynCall_iiiiii=function(){return d.asm.dynCall_iiiiii.apply(null,arguments)};d.dynCall_iiiiiid=function(){return d.asm.dynCall_iiiiiid.apply(null,arguments)};
d.dynCall_iiiiiii=function(){return d.asm.dynCall_iiiiiii.apply(null,arguments)};d.dynCall_iiiiiiii=function(){return d.asm.dynCall_iiiiiiii.apply(null,arguments)};d.dynCall_iiiiiiiii=function(){return d.asm.dynCall_iiiiiiiii.apply(null,arguments)};d.dynCall_iiiiij=function(){return d.asm.dynCall_iiiiij.apply(null,arguments)};d.dynCall_v=function(){return d.asm.dynCall_v.apply(null,arguments)};d.dynCall_vi=function(){return d.asm.dynCall_vi.apply(null,arguments)};
d.dynCall_vii=function(){return d.asm.dynCall_vii.apply(null,arguments)};d.dynCall_viii=function(){return d.asm.dynCall_viii.apply(null,arguments)};d.dynCall_viiii=function(){return d.asm.dynCall_viiii.apply(null,arguments)};d.dynCall_viiiii=function(){return d.asm.dynCall_viiiii.apply(null,arguments)};d.dynCall_viiiiii=function(){return d.asm.dynCall_viiiiii.apply(null,arguments)};d.dynCall_viijii=function(){return d.asm.dynCall_viijii.apply(null,arguments)};d.asm=Fb;
d.then=function(a){if(d.calledRun)a(d);else{var b=d.onRuntimeInitialized;d.onRuntimeInitialized=function(){b&&b();a(d)}}return d};J=function Gb(){d.calledRun||Hb();d.calledRun||(J=Gb)};
function Hb(){function a(){if(!d.calledRun&&(d.calledRun=!0,!la)){Ia||(Ia=!0,G(Fa));G(Ga);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var a=d.postRun.shift();Ha.unshift(a)}G(Ha)}}if(!(0<H)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Ja();G(Ea);0<H||d.calledRun||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},
1);a()},1)):a())}}d.run=Hb;function w(a){if(d.onAbort)d.onAbort(a);void 0!==a?(ia(a),v(a),a=JSON.stringify(a)):a="";la=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}d.abort=w;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();d.noExitRuntime=!0;Hb();


  return Module;
};
if (typeof exports === 'object' && typeof module === 'object')
    module.exports = Module;
  else if (typeof define === 'function' && define['amd'])
    define([], function() { return Module; });
  else if (typeof exports === 'object')
    exports["Module"] = Module;
  