env:
  browser: true
  es6: true
extends: airbnb
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  max-len:
    - 2
    - code: 150
      ignoreComments: true
  no-multi-spaces: 0
  no-param-reassign: 0
  no-underscore-dangle: 0
  no-return-assign: 0
  prefer-destructuring: 0
  key-spacing: 0
  arrow-body-style: 0
  import/no-cycle: 0
